### PR TITLE
installer: refactor & improve the Bash-based installer script

### PR DESCRIPTION
**Pull request by Krotki**
Hej, I wanted to improve a bit (pimp) install script for linux with a few features:
- download latest SHA and ASSET_ID's silently
- download executable and template with progress bar
- ask user if to create a symlink
- add sudo to symlink creation (on my system it was required to access /usr/local/bin)
- unpack and override only newer files for templates.zip

### CODE REVIEW

**Comment by Wertzui123** [comment]
(I've just changed your title so it matches the commit message norm in this repository.)

**Comment by Krotki** [comment]
As for IFS I was experimenting with read command and delimiters, but it is completely unnecessary here. Removed.

I also rephrased the question. Is it cleaner ?

**Comment by Wertzui123** [comment]
I'd probably phrase it something like ```Make the `aspl` command available everywhere (by creating a symlink in /usr/local/bin)?```

**Comment by Wertzui123** [comment]
And by the way, I'm currently thinking about removing `install_ci.sh` because the CI/CD workflow can basically use the regular installer script nowadays. If we did this, we wouldn't have to update that script as well. Just so you know, I might not instantly merge your PR.

**Comment by Wertzui123** [comment]
> I'd probably phrase it something like Make the `aspl` command available everywhere (by creating a symlink in /usr/local/bin)?

So, what do you think? Shall we change it, or do you think people will understand the prompt even when they're not very familiar with shells and file systems?

I can merge the PR after we've settled on a wording.

**Pull request merged**
